#!/bin/sh

# Solo correr validaciones si NO estamos en un entorno CI
if [ "$CI" != "true" ]; then
  echo "Running lint-staged..."
  npx lint-staged

  echo "Typechecking frontend..."
  pnpm -C frontend typecheck

  echo "Typechecking backend..."
  pnpm -C backend typecheck
fi
