name: Deploy to VPS

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'db/**'
      - 'nginx/**'
      - '.github/workflows/deploy.yml'
      - 'docker-compose.prod.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar comandos en el VPS vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/fernetloshorneros
            git pull origin main
            docker compose -f docker-compose.prod.yml up -d --build
            docker image prune -f